### PR TITLE
Fake data

### PR DESCRIPTION
**Pull request by hhummel**
Create fake data for models exposed in the REST API

### CODE REVIEW

**Comment by hhummel** [comment]
Looks like there's some unit testing to fix!

**Comment by mariekers** [comment]
I think @mattusifer and @MikeyManoguerra might be better at checking this

**Comment by hhummel** [comment]
One improvement that occurred to me is to add a random.seed() so the seeded values are reproducible.

**Comment by hhummel** [comment]
I admit I had a little fun with it.

**Pull request merged**
