### PR TITLE
Renamed getFrontDeskEvents method to createNewFrontDeskEvents in 

### PR DESCRIPTION
**Pull request by JackRyan1989**
frontend.

### CODE REVIEW

**Comment by ThrowsException** [comment]
why `createNewFrontDeskEvent` when the operation is a get? That seems like it would imply a PUT or POST operation and make the `postFrontDeskEvent` confusing.

**Comment by ThrowsException** [comment]
greping the code it doesn't even look like `getFrontDeskEvent` is even used can it just be removed?

**Comment by JackRyan1989** [comment]
This is in response to Issue #365, I'm not sure what the logic was initially behind the request to change the name.

**Comment by JackRyan1989** [comment]
If there's no plan to use the command in the future I'm ok with removing the method.

**Comment by JackRyan1989** [comment]
@ThrowsException Ok, I changed back the api endpoints, and just made a small change in the ParticipantStore.js file to make the error messages a consistent format. Let me know if you have any questions or concerns.

**Review by ThrowsException — APPROVED** [review]

**Pull request merged**
