### PR TITLE
Search participant

### PR DESCRIPTION
**Pull request by robb33**
Update to the frontend

### CODE REVIEW

**Comment by robb33** [comment]
a lot of these changes are FE...I can't see anything that would be a show stopper...would like to push this up so we can move forward

**Comment by mariekers** [comment]
@bkarlovitz or @Nkdiaz - would either of you mind reviewing this?

**Comment by robb33** [comment]
the sooner the better....I really want to set a baseline here...

**Comment by robb33** [comment]
we need to stop this request....James established a cleaner baseline....I can move some of this over without conflict

**Pull request closed without merging**
